DynamodbActivityTable:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
      - AttributeName: pKey
        AttributeType: S
      - AttributeName: sKey
        AttributeType: S
    KeySchema:
      - AttributeName: pKey
        KeyType: HASH
      - AttributeName: sKey
        KeyType: RANGE
    BillingMode: PAY_PER_REQUEST
    TableName: Tlog-${self:provider.stage}-ACTIVITY
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    TimeToLiveSpecification:
      AttributeName: expiration
      Enabled: true