function:
  handler: src/activityInsert/index.insertActivity
  layers:
    - !Ref TlogLayerLambdaLayer
  package:
    individually: true
    patterns:
      - "!**/*"
      - "src/activityInsert/*.js"
      - "src/shared/**"
