function:
  description: nm generate TLog data - ${self:provider.stage}
  name: nm-generate-t-log-data-${self:provider.stage}
  handler: src/generateTLogData/index.handler
  events:
    - stream:
        type: dynamodb
        arn: !GetAtt MerchantOrderTable.StreamArn
        batchWindow: 10
  layers:
    - !Ref TlogLayerLambdaLayer
  package:
    individually: true
    patterns:
      - "!**/*"
      - "src/generateTLogData/**"
      - "src/shared/**"