function:
  handler: src/mapInsertDb/index.handler
  events:
    - sqs:
        arn: !GetAtt QueueToTriggerLambda.Arn
        batchSize: 1
  layers:
    - !Ref TlogLayerLambdaLayer
  package:
    individually: true
    patterns:
      - "!**/*"
      - "src/mapInsertDb/*.js"
      - "src/activityInsert/*.js"
      - "src/shared/**"
      - "config/queues/snsToDynamo"
